### ISSUE TITLE
Replace LiveReload with BrowserSync

### ISSUE THREAD

**Issue by jameswilson** [BluesparkLabs/gulp-frontend-tasks#2]
Let's switch to BrowserSync, which is a little bit more robust than LiveReload:

* BrowserSync doesn't require a browser extension (like LiveReload does) -- this will simplify install steps.
* BrowserSync can sync across multiple browsers/devices, and even sync/maintain scroll position across those devices.

Source: https://www.slant.co/versus/5065/5066/~livereload_vs_browsersync
Adtl. Info: https://www.agencyascend.com/blog/using-gulp-automate-streamline-your-drupal-theme-development

**Comment by salvamomo** [comment]
+1!

I've been using BSync recently in a side project and the experience was overall better. I think it'll be an improvement in our stack over LR.
